<a href="https://colab.research.google.com/github/mohdrab01/Machine-Learning-Lab-Tasks/blob/main/ML_Week10(i).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ML - Week 10(i) - 07-06-2021
# 18071A0591

---

## 1. Demonstrate Naive Bayes Classifier ( Iris Dataset)

In [1]:
!wget https://raw.githubusercontent.com/ApoorvRusia/Naive-Bayes-classification-on-Iris-dataset/master/iris.csv

--2021-06-07 08:55:27--  https://raw.githubusercontent.com/ApoorvRusia/Naive-Bayes-classification-on-Iris-dataset/master/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3716 (3.6K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   3.63K  --.-KB/s    in 0s      

2021-06-07 08:55:27 (68.3 MB/s) - ‘iris.csv’ saved [3716/3716]



In [2]:
# Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd

In [40]:
# Importing the dataset
dataset = pd.read_csv('iris.csv')

In [41]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
#Spliting the dataset in independent and dependent variables
X = dataset.iloc[:,:4].values
y = dataset['species'].values

In [43]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

In [44]:
# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [45]:
# Fitting Naive Bayes Classification to the Training set with linear kernel
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [46]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

['virginica' 'virginica' 'setosa' 'setosa' 'setosa' 'virginica'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'setosa' 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'virginica' 'versicolor' 'virginica' 'setosa' 'virginica' 'versicolor']


In [47]:
y_test.shape, y_pred.shape

((30,), (30,))

In [48]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
# top 5
y_compare[:5,:]

array([['virginica', 'virginica'],
       ['virginica', 'virginica'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa']], dtype=object)

In [49]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 0  8  1]
 [ 0  1  9]]


In [50]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))

Correct predictions:  28
False predictions 2


Accuracy of the Naive Bayes Clasification is:  0.9333333333333333


## 2. Demonstrate Naive Bayes Classifier ( Diabetes Dataset)

In [51]:
from sklearn.datasets import load_diabetes
dataset = load_diabetes()

In [52]:
X = pd.DataFrame(dataset.data)
X.head()

0         1         2  ...         7         8         9
0  0.038076  0.050680  0.061696  ... -0.002592  0.019908 -0.017646
1 -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068330 -0.092204
2  0.085299  0.050680  0.044451  ... -0.002592  0.002864 -0.025930
3 -0.089063 -0.044642 -0.011595  ...  0.034309  0.022692 -0.009362
4  0.005383 -0.044642 -0.036385  ... -0.002592 -0.031991 -0.046641

[5 rows x 10 columns]

In [53]:
X.columns.shape

(10,)

In [54]:
y = pd.DataFrame(dataset.target)
y.head()

0
0  151.0
1   75.0
2  141.0
3  206.0
4  135.0

In [55]:
y.columns.shape

(1,)

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

In [57]:
# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [58]:
# Fitting Naive Bayes Classification to the Training set with linear kernel
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [59]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

[233. 134. 214. 258. 258. 138. 118. 197. 200. 107.  91. 258. 138. 202.
 134. 160. 233.  71. 196. 200. 258. 138. 200. 245. 138. 258. 138. 124.
 258. 258. 134. 107. 258. 134. 197. 160. 134. 257. 196. 134. 113. 138.
 134. 138. 138. 200. 138.  59. 134. 258.  77. 134. 245. 134. 258. 196.
 258. 200. 139.  71. 138.  48. 134. 150. 281. 107. 233.  70. 134. 258.
 258. 258. 258.  64. 200. 110. 134.  77. 134. 182. 138. 258. 258. 107.
 107. 107. 134. 138. 128.]


In [60]:
y_test.shape, y_pred.shape

((89, 1), (89,))

In [61]:
y_test[0].shape

(89,)

In [62]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test[0],y_pred)).T
y_compare[:5,:]

array([[243., 233.],
       [ 42., 134.],
       [206., 214.],
       [ 52., 258.],
       [215., 258.]])

In [63]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [64]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))

Correct predictions:  1
False predictions 88


Accuracy of the Naive Bayes Clasification is:  0.011235955056179775


## 3. Demonstrate Naive Bayes Classifier ( Fruit Dataset)

In [65]:
!wget https://raw.githubusercontent.com/houssamboudiar/Predicting-fruits-using-Height-Weight-ML/master/fruit_data_with_colors.csv

--2021-06-07 09:19:38--  https://raw.githubusercontent.com/houssamboudiar/Predicting-fruits-using-Height-Weight-ML/master/fruit_data_with_colors.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2309 (2.3K) [text/plain]
Saving to: ‘fruit_data_with_colors.csv’

fruit_data_with_col 100%[===================>]   2.25K  --.-KB/s    in 0s      

2021-06-07 09:19:38 (37.4 MB/s) - ‘fruit_data_with_colors.csv’ saved [2309/2309]



In [66]:
# Importing the dataset
dataset = pd.read_csv('fruit_data_with_colors.csv')

In [67]:
dataset.head()

fruit_label fruit_name fruit_subtype   mass  width  height  color_score
0            1      apple  granny_smith  192.0    8.4     7.3         0.55
1            1      apple  granny_smith  180.0    8.0     6.8         0.59
2            1      apple  granny_smith  176.0    7.4     7.2         0.60
3            2   mandarin      mandarin   86.0    6.2     4.7         0.80
4            2   mandarin      mandarin   84.0    6.0     4.6         0.79

In [83]:
dataset.isnull().sum()

fruit_label      0
fruit_name       0
fruit_subtype    0
mass             0
width            0
height           0
color_score      6
dtype: int64

In [86]:
dataset = dataset.fillna(dataset['color_score'].mean())
dataset.isnull().sum()

fruit_label      0
fruit_name       0
fruit_subtype    0
mass             0
width            0
height           0
color_score      0
dtype: int64

In [87]:
#Spliting the dataset in independent and dependent variables
X = dataset.iloc[:,3:7].values
y = dataset['fruit_name'].values

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

In [89]:
# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [90]:
# Fitting Naive Bayes Classification to the Training set with linear kernel
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [91]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

['apple' 'apple' 'lemon' 'apple' 'lemon' 'orange' 'apple' 'orange'
 'orange' 'apple' 'orange' 'apple']


In [93]:
y_test.shape, y_pred.shape

((12,), (12,))

In [94]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
y_compare[:5,:]

array([['apple', 'apple'],
       ['apple', 'apple'],
       ['lemon', 'lemon'],
       ['apple', 'apple'],
       ['lemon', 'lemon']], dtype=object)

In [95]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[6 0 1]
 [0 2 0]
 [0 0 3]]


In [96]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))

Correct predictions:  11
False predictions 1


Accuracy of the Naive Bayes Clasification is:  0.9166666666666666


## 4. kNN Classifier ( Fruit Dataset)

In [99]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [101]:
predictions = knn.predict(X_test)

In [104]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.9166666666666666
[[6 0 1]
 [0 2 0]
 [0 0 3]]
              precision    recall  f1-score   support

       apple       1.00      0.86      0.92         7
       lemon       1.00      1.00      1.00         2
      orange       0.75      1.00      0.86         3

    accuracy                           0.92        12
   macro avg       0.92      0.95      0.93        12
weighted avg       0.94      0.92      0.92        12



In [107]:
# Eucledian dist
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(metric='euclidean')
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [108]:
predictions = knn.predict(X_test)

In [109]:
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.9166666666666666
[[6 0 1]
 [0 2 0]
 [0 0 3]]
              precision    recall  f1-score   support

       apple       1.00      0.86      0.92         7
       lemon       1.00      1.00      1.00         2
      orange       0.75      1.00      0.86         3

    accuracy                           0.92        12
   macro avg       0.92      0.95      0.93        12
weighted avg       0.94      0.92      0.92        12

